
CANCEL_BUTTON_ACTION = "cancel_button_select"
EDIT_EVENT_ACTION = "submit_edit_event_button"
ADD_EVENT_ACTION = "submit_add_event_button"
ADD_AO_ACTION = "submit_add_ao_button"
EDIT_AO_ACTION = "submit_edit_ao_button"
EDIT_SCHEDULE_ACTION = "manage_schedule_option_button"
MANAGE_SCHEDULE_ACTION = "manage_schedule_button"
EDIT_SETTINGS_ACTION = "submit_general_settings"
REFRESH_ACTION = "refresh_home"
